<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to bestclassifier • bestclassifier</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to bestclassifier">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">bestclassifier</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/introduction_to_bestclassifier.html">Introduction to bestclassifier</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Introduction to bestclassifier</h1>
                        <h4 class="author">Shane Ross</h4>
            
            <h4 class="date">2018-12-21</h4>
      
      
      <div class="hidden name"><code>introduction_to_bestclassifier.Rmd</code></div>

    </div>

    
    
<div id="identify-the-best-machine-learning-binary-classification-model" class="section level2">
<h2 class="hasAnchor">
<a href="#identify-the-best-machine-learning-binary-classification-model" class="anchor"></a>Identify the best machine learning binary classification model</h2>
<p>When creating binary classification models, you must:</p>
<pre><code>+ identify your desired machine learning models

+ tune the parameters for each model

+ train each model on your training data

+ test the models on your testing data

+ compare the results to find the best model</code></pre>
<p>bestclassifier facilitates this complex, arduous process by allowing you to complete all of those tasks in one function</p>
<pre><code>+ This function supports eight elite machine learning binary classification models, including:

    - logistic regression
    
    - lasso regression
    
    - random forest
    
    - extreme gradient boosting
    
    - support vector machine
    
    - artificial neural network
    
    - latent dirichlet allocation
    
    - k nearest neighbors</code></pre>
<div id="parameters-in-the-best-classifier-function" class="section level3">
<h3 class="hasAnchor">
<a href="#parameters-in-the-best-classifier-function" class="anchor"></a>Parameters in the best.classifier function</h3>
<div id="data" class="section level4">
<h4 class="hasAnchor">
<a href="#data" class="anchor"></a>data</h4>
<ul>
<li>
<strong>data</strong> specifies the dataframe on which the user would like to employ the binary classification models.
<ul>
<li>Ex: data = CCD_data</li>
</ul>
</li>
</ul>
</div>
<div id="form" class="section level4">
<h4 class="hasAnchor">
<a href="#form" class="anchor"></a>form</h4>
<ul>
<li>
<strong>form</strong> describes the formula the user would like to use to guide the binary classification models. The formula should be structured: dependent_variable ~ independent1 + independent2 + …
<ul>
<li>Ex: form = Class ~ .</li>
</ul>
</li>
</ul>
</div>
<div id="p" class="section level4">
<h4 class="hasAnchor">
<a href="#p" class="anchor"></a>p</h4>
<ul>
<li>
<strong>p</strong> specifies the percentage of the dataset used to train the model. This parameter must be a number in between 0 and 1.
<ul>
<li>Ex: p = .7</li>
</ul>
</li>
</ul>
</div>
<div id="method" class="section level4">
<h4 class="hasAnchor">
<a href="#method" class="anchor"></a>method</h4>
<ul>
<li>
<strong>method</strong> specifies the resampling method instituted to train the binary classification models. The potential methods involve a series of boot and cross validation models, including boot, boot632, optimism_boot, boot_all, repeatedcv, LOOCV, LGOCV, none, oob, adaptive_cv, adaptive_boot, adaptive_LGOCV.
<ul>
<li>Ex: method = “repeatedcv”</li>
</ul>
</li>
</ul>
</div>
<div id="number" class="section level4">
<h4 class="hasAnchor">
<a href="#number" class="anchor"></a>number</h4>
<ul>
<li>
<strong>number</strong> indicates the amount of folds or repeated iterations employed to train the binary classification models. While more folds or sampling iterations will generate a more accurate result on the training dataset, increasing the number of folds can make the model suceptible to overfitting biases.
<ul>
<li>Ex: number = 5</li>
</ul>
</li>
</ul>
</div>
<div id="repeats" class="section level4">
<h4 class="hasAnchor">
<a href="#repeats" class="anchor"></a>repeats</h4>
<ul>
<li>Solely pertinent to the repeated cross validation method, <strong>repeats</strong> indicates the number of complete sets of folds for k-fold cross validation. By creating more data partitions with k-subsets, the number parameter can dramatically reduce the variance of the training model but will also increase computation time.
<ul>
<li>Ex: repeats = 1</li>
</ul>
</li>
</ul>
</div>
<div id="tunelength" class="section level4">
<h4 class="hasAnchor">
<a href="#tunelength" class="anchor"></a>tuneLength</h4>
<ul>
<li>
<strong>tuneLength</strong> indicates the number of values the model will analyze for each tuning parameter in order to find the optimal tuning levels.
<ul>
<li>tuneLength = 5</li>
</ul>
</li>
</ul>
</div>
<div id="positive" class="section level4">
<h4 class="hasAnchor">
<a href="#positive" class="anchor"></a>positive</h4>
<ul>
<li>
<strong>positive</strong> reflects the argument of the dependent variable that the binary classification models aim to predict. This object must be a string.
<ul>
<li>Ex: positive = “Default”</li>
</ul>
</li>
</ul>
</div>
<div id="model" class="section level4">
<h4 class="hasAnchor">
<a href="#model" class="anchor"></a>model</h4>
<ul>
<li>
<strong>model</strong> indicates the specific binary classification models trained by bestclassifier. These options include logistic regresion, lasso regression, random forest, extreme gradient boosting, support vector machine, artificial neural network, latent dirichlet allocation, and k-nearest neighbors models.
<ul>
<li>Ex: model = c(“log_reg”, “lasso”, “rf”, “svm”, “xgboost”, “ann”, “lda”, “knn”)</li>
</ul>
</li>
</ul>
</div>
<div id="set_seed" class="section level4">
<h4 class="hasAnchor">
<a href="#set_seed" class="anchor"></a>set_seed</h4>
<ul>
<li>
<strong>set_seed</strong> provides a reproducible random number generator so the user can run a model multiple times and receive identical results. This parameter must be a numeric object.
<ul>
<li>Ex: set_seed = 1234</li>
</ul>
</li>
</ul>
</div>
<div id="subset_train" class="section level4">
<h4 class="hasAnchor">
<a href="#subset_train" class="anchor"></a>subset_train</h4>
<ul>
<li>After the data has been divided into a training and testing dataset, <strong>subset_train</strong> will reduce the size of the training data in order to generate the binary classification models more quickly. This parameter is used to decrease computation time when the training dataset is especially large and the user does not have time to wait for the results. However, performance can suffer when training a model based on a fraction of the training data. This parameter accepts numeric objects between 0 and 1.
<ul>
<li>Ex: subset_train = .1</li>
</ul>
</li>
</ul>
</div>
<div id="desired_metric" class="section level4">
<h4 class="hasAnchor">
<a href="#desired_metric" class="anchor"></a>desired_metric</h4>
<ul>
<li>
<strong>desired_metric</strong> specifies the metric employed to calculate the best binary classificaiton model. The available performance metrics include AUC or Accuracy.
<ul>
<li>Ex: desired_metric = “ROC”</li>
<li>Ex: desired_metric = “Accuracy”</li>
</ul>
</li>
</ul>
</div>
</div>
</div>
<div id="data-ccd_data" class="section level2">
<h2 class="hasAnchor">
<a href="#data-ccd_data" class="anchor"></a>Data: CCD_data</h2>
<p>In order to explore the best.classifier function, we will use the CCD dataset. This dataset contains default status and payment information for all credit card customers transacting with a Taiwanese bank in 2005.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">CCD &lt;-<span class="st"> </span>bestclassifier<span class="op">::</span>CCD
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(CCD)
<span class="co">#&gt; 'data.frame':    29728 obs. of  24 variables:</span>
<span class="co">#&gt;  $ default.payment.next.month: Factor w/ 2 levels "Nondefault","Default": 2 2 1 1 1 1 1 1 1 1 ...</span>
<span class="co">#&gt;  $ LIMIT                     : num  20000 120000 90000 50000 50000 50000 100000 140000 20000 200000 ...</span>
<span class="co">#&gt;  $ SEX                       : Factor w/ 2 levels "M","F": 2 2 2 2 1 1 2 2 1 2 ...</span>
<span class="co">#&gt;  $ EDUCATION                 : Factor w/ 4 levels "Other","Graduate_School",..: 3 3 3 3 3 2 3 4 4 4 ...</span>
<span class="co">#&gt;  $ MARRIAGE                  : Factor w/ 4 levels "Other","Married",..: 2 3 3 2 2 3 3 2 3 3 ...</span>
<span class="co">#&gt;  $ AGE                       : num  24 26 34 37 57 37 23 28 35 34 ...</span>
<span class="co">#&gt;  $ REPAID.SEPT               : Factor w/ 6 levels "1 Month Delay",..: 2 5 6 6 5 6 6 6 4 6 ...</span>
<span class="co">#&gt;  $ REPAID.AUG                : Factor w/ 5 levels "1-2 Month Delay",..: 1 1 5 5 5 5 4 5 3 5 ...</span>
<span class="co">#&gt;  $ REPAID.JULY               : Factor w/ 5 levels "1-2 Month Delay",..: 4 5 5 5 4 5 4 1 3 1 ...</span>
<span class="co">#&gt;  $ REPAID.JUNE               : Factor w/ 5 levels "1-2 Month Delay",..: 4 5 5 5 5 5 5 5 3 5 ...</span>
<span class="co">#&gt;  $ REPAID.MAY                : Factor w/ 5 levels "1-2 Month Delay",..: 3 5 5 5 5 5 5 5 4 5 ...</span>
<span class="co">#&gt;  $ REPAID.APR                : Factor w/ 5 levels "1-2 Month Delay",..: 3 1 5 5 5 5 4 5 4 4 ...</span>
<span class="co">#&gt;  $ BILL_SEPT                 : num  3913 2682 29239 46990 8617 ...</span>
<span class="co">#&gt;  $ BILL_AUG                  : num  3102 1725 14027 48233 5670 ...</span>
<span class="co">#&gt;  $ BILL_JULY                 : num  689 2682 13559 49291 35835 ...</span>
<span class="co">#&gt;  $ BILL_JUNE                 : num  0 3272 14331 28314 20940 ...</span>
<span class="co">#&gt;  $ BILL_MAY                  : num  0 3455 14948 28959 19146 ...</span>
<span class="co">#&gt;  $ BILL_APR                  : num  0 3261 15549 29547 19131 ...</span>
<span class="co">#&gt;  $ PAYMENT_SEPT              : num  0 0 1518 2000 2000 ...</span>
<span class="co">#&gt;  $ PAYMENT_AUG               : num  689 1000 1500 2019 36681 ...</span>
<span class="co">#&gt;  $ PAYMENT_JULY              : num  0 1000 1000 1200 10000 657 0 432 0 50 ...</span>
<span class="co">#&gt;  $ PAYMENT_JUNE              : num  0 1000 1000 1100 9000 ...</span>
<span class="co">#&gt;  $ PAYMENT_MAY               : num  0 0 1000 1069 689 ...</span>
<span class="co">#&gt;  $ PAYMENT_APR               : num  0 2000 5000 1000 679 ...</span></code></pre></div>
</div>
<div id="interpreting-the-output-generated-by-best-classifier" class="section level2">
<h2 class="hasAnchor">
<a href="#interpreting-the-output-generated-by-best-classifier" class="anchor"></a>Interpreting the output generated by best.classifier</h2>
<p>In the example below, I am seeking the machine learning model that produces the highest AUC when classifying credit card default. These models will be predicting the “Default” category in the Class variable by using all of the predictors in the dataset. Because the CCD data contains nearly 30,000 observations, I am training the model on 1% of the training dataset for fast results.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(bestclassifier)
<span class="kw"><a href="../reference/bestclassifier.html">bestclassifier</a></span>(<span class="dt">data =</span> CCD, <span class="dt">form =</span> default.payment.next.month <span class="op">~</span><span class="st"> </span>., <span class="dt">p =</span> <span class="fl">0.7</span>, <span class="dt">method =</span> 
<span class="st">"repeatedcv"</span>, <span class="dt">number =</span> <span class="dv">5</span>, <span class="dt">repeats =</span> <span class="dv">1</span>, <span class="dt">tuneLength =</span> <span class="dv">5</span>, 
<span class="dt">positive =</span><span class="st">"Default"</span>, <span class="dt">model =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"log_reg"</span>, <span class="st">"lasso"</span>, <span class="st">"lda"</span>, 
<span class="st">"svm"</span>, <span class="st">"lda"</span>, <span class="st">"knn"</span>, <span class="st">"ann"</span>, 
<span class="st">"xgboost"</span>),
<span class="dt">set_seed =</span> <span class="dv">1234</span>, <span class="dt">subset_train =</span> .<span class="dv">01</span>, <span class="dt">desired_metric =</span> <span class="st">"ROC"</span>)
<span class="co">#&gt; Your best binary classification model is lasso_reg yielding an AUC of 0.6495 </span>
<span class="co">#&gt; </span></code></pre></div>
<p><img src="introduction_to_bestclassifier_files/figure-html/best.classifier-1.png" width="700"></p>
<pre><code>#&gt; Confusion Matrix and Statistics
#&gt; 
#&gt;             Reference
#&gt; Prediction   Nondefault Default
#&gt;   Nondefault       6912    1916
#&gt;   Default            29      61
#&gt;                                           
#&gt;                Accuracy : 0.7819          
#&gt;                  95% CI : (0.7732, 0.7904)
#&gt;     No Information Rate : 0.7783          
#&gt;     P-Value [Acc &gt; NIR] : 0.2112          
#&gt;                                           
#&gt;                   Kappa : 0.0405          
#&gt;  Mcnemar's Test P-Value : &lt;2e-16          
#&gt;                                           
#&gt;             Sensitivity : 0.03085         
#&gt;             Specificity : 0.99582         
#&gt;          Pos Pred Value : 0.67778         
#&gt;          Neg Pred Value : 0.78296         
#&gt;              Prevalence : 0.22169         
#&gt;          Detection Rate : 0.00684         
#&gt;    Detection Prevalence : 0.01009         
#&gt;       Balanced Accuracy : 0.51334         
#&gt;                                           
#&gt;        'Positive' Class : Default         
#&gt; </code></pre>
<div id="understanding-the-bar-graph" class="section level3">
<h3 class="hasAnchor">
<a href="#understanding-the-bar-graph" class="anchor"></a>Understanding the Bar Graph</h3>
<p>According to the bar graph, the lasso regression model performed the best on the training data, depicting an AUC of .6495.</p>
</div>
<div id="analyzing-the-confusion-matrix" class="section level3">
<h3 class="hasAnchor">
<a href="#analyzing-the-confusion-matrix" class="anchor"></a>Analyzing the Confusion Matrix</h3>
<p>Random Forest results on testing data:</p>
<pre><code>+ Accuracy: 78.2%

+ Sensitivity: 3.1%

+ Specificity: 99.6%

+ Positive Predictive Value: 67.8%

+ Negative Predictive Value: 78.3%</code></pre>
<div id="accuracy" class="section level4">
<h4 class="hasAnchor">
<a href="#accuracy" class="anchor"></a>Accuracy</h4>
<ul>
<li>
<em>Accuracy</em> describes the total number of default statuses that the model classified correctly. In our model, an Accuracy of 78.2% indicates that the model correctly identified whether a customer did or did not default 78.2% of the time.</li>
</ul>
</div>
<div id="sensitivity" class="section level4">
<h4 class="hasAnchor">
<a href="#sensitivity" class="anchor"></a>Sensitivity</h4>
<ul>
<li>
<em>Sensitivity</em> indcates the percentage of total credit card defaults captured by the model. The model’s sensitivity of 3.1% indicates that this model was able to predict 3.1% of the total defaults.</li>
</ul>
</div>
<div id="specificity" class="section level4">
<h4 class="hasAnchor">
<a href="#specificity" class="anchor"></a>Specificity</h4>
<ul>
<li>
<em>Specificity</em> depicts the percentage of total non-defaults detected by the model. The specificity value of 99.6% reveals that the model correctly classified 99.6% of clients who did not default.</li>
</ul>
</div>
<div id="positive-predictive-value" class="section level4">
<h4 class="hasAnchor">
<a href="#positive-predictive-value" class="anchor"></a>Positive Predictive Value</h4>
<ul>
<li>
<em>Positive Predictive Value</em> indicates the accuracy of the model when it predicted that a customer would default. The PPV score of 67.8% demonstrates that the model was 67.8% accurate when it predicted that the customer would default.</li>
</ul>
</div>
<div id="negative-predictive-value" class="section level4">
<h4 class="hasAnchor">
<a href="#negative-predictive-value" class="anchor"></a>Negative Predictive Value</h4>
<ul>
<li>
<em>Negative Predictive Value</em> describes the model’s precision when it forecasted that a customer would not default. As depicted in the model, an NPV score of 78.3% illustrates that the model was 78.3% accurate when it predicted that the client would not default.</li>
</ul>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#identify-the-best-machine-learning-binary-classification-model">Identify the best machine learning binary classification model</a></li>
      <li><a href="#data-ccd_data">Data: CCD_data</a></li>
      <li><a href="#interpreting-the-output-generated-by-best-classifier">Interpreting the output generated by best.classifier</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Shane Ross.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
